 (let x = 1 in y + 4)  + ( if x then y else z ) + (lambda x. x + fun f with w = e in p ) + (readString + print x + isNil x + !x + #x + Nil + "pit") + ((let x = 1 in y + 4)  + ( if x then y else z ) + (lambda x. x + fun f with w = e in p ) + (readString + print x + isNil x + !x + #x + Nil + "pit"))+readInt
|
( "pie is pretty darn good?" + things + print expression )
|
( fun f with x1, x2, x3 = e in p )
|
( this <> that <= other >= than > oh < hai )
|
(i@a@m@a@l@i@s@t) 
